lhl-tdd/config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index'
  resources :customers, only: [:index, :new, :create, :show]
end

lhl-tdd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lhl-tdd/app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true

  def self.customers_in_alphabetical_order
    order(:name)
  end
end

lhl-tdd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lhl-tdd/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.customers_in_alphabetical_order
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash.notice = "Successfully added #{@customer.name}."
      redirect_to customers_path
    else
      flash.now.alert = "Error creating customer."
      render :new
    end
  end

  private

  def customer_params
    params.require(:customer).permit(
      :name,
      :email,
      :birthday
    )
  end
end

lhl-tdd/app/helpers/application_helper.rb
module ApplicationHelper
end

lhl-tdd/app/views/customers/index.html.erb
<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="2">
        <%= link_to "Add Customer", new_customer_path%>
      </td>
    </tr>
  </tbody>
</table>

lhl-tdd/app/views/customers/new.html.erb
<h1>Add Customer</h1>

<%= form_for @customer do |f| %>
  <div>
    <%= f.label :name%>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :birthday %>
    <%= f.date_select :birthday, end_year: 1900, start_year: Date.current.year %>
  </div>
  <div>
    <%= f.submit "Create Customer"%>
  </div>
<% end %>

lhl-tdd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LhlTddDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= flash.notice %>
    </div>
    <%= yield %>
  </body>
</html>